version: "3.8"
services:
  redis:
    # We use alpine versions because they are lightweight and download faster
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  postgres:
    # We use postgres 15 for our analytics database
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llm_cache
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
